// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCoreHooksConsole.Models
{
    public partial class ShopDefault
    {
        public long ShopDefault_Id { get; set; }
        public long ShopDefault_ShopId { get; set; }
        public string ShopDefault_GroupTypeDef { get; set; }
        public string ShopDefault_Key { get; set; }
        public string ShopDefault_Value { get; set; }
        public DateTime ShopDefault_CreatedDateTime { get; set; }
        public string ShopDefault_CreatedUser { get; set; }
        public byte ShopDefault_UpdatedTimes { get; set; }
        public DateTime ShopDefault_UpdatedDateTime { get; set; }
        public string ShopDefault_UpdatedUser { get; set; }
        public bool ShopDefault_ValidFlag { get; set; }
    }
}