version: '3'
services:
  ap_web:
    image: knight/web_redis
    ports:
      - '8080:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis_Host=redis_server
    depends_on:
      - db_redis
  db_redis:
    image: redis
    container_name: redis_server