version: '3.7'
services:
 tag-system:
   build: ./TagSystem
   container_name: tag-system
   ports:
    - "8080:80"
   depends_on:
    - "dynamodb-local"
   links:
    - "dynamodb-local"
   environment:
    - AWS_ACCESS_KEY_ID='DUMMYIDEXAMPLE'
    - AWS_SECRET_ACCESS_KEY='DUMMYEXAMPLEKEY'
    - REGION='eu-west-1'
 dynamodb-local:
   image: amazon/dynamodb-local:latest
   container_name: dynamodb-local
   ports:
    - "8000:8000"