@host = http://localhost:5000

### Get Table List
GET {{host}}/api/tables

### Create Table
@tableName = Table02
POST {{host}}/api/tables/{{tableName}}

### Delete Table
DELETE {{host}}/api/tables/{{tableName}}


### Get Tag by TagName
@tagId = 1c9f54c59df9
GET {{host}}/api/tags/{{tagId}}

### Get Tag by TagName. # = %23
@shopId = 44
@tagId = TAG%231c9f54c59df9
GET {{host}}/api/tags/{{shopId}}/{{tagId}}

### Query Tag
POST {{host}}/api/tags/query
Content-Type: application/json

{
    "PK": "TAG#001"
}

### Create Tag
POST {{host}}/api/tags
Content-Type: application/json

{
  "pk": "TAG#111",
  "sk": "44#222",
  "sale_page_id": "123",
  "multipal_language_content": "{ \"en-US\":\"Size_M\"}",
  "tag_name": "尺寸_A",
  "shop_id": "44",
  "tag_id": "333"
}

### Create Tag List
POST {{host}}/api/tags/list
Content-Type: application/json

[
  {
    "pk": "TAG#001",
    "sk": "46#0011",
    "sale_page_id": "00111",
    "multipal_language_content": "{ \"en-US\":\"Size_M\"}",
    "tag_name": "尺寸_A",
    "shop_id": "46",
    "tag_id": "001"
  },
  {
    "pk": "TAG#002",
    "sk": "35#0022",
    "sale_page_id": "00222",
    "multipal_language_content": "{ \"en-US\":\"Size_M\"}",
    "tag_name": "Style_Romance",
    "shop_id": "35",
    "tag_id": "002"
  }
]