@host = http://localhost:5000

### Get Table List
GET {{host}}/api/data

### Create Table
@tableName = T003
POST {{host}}/api/data/{{tableName}}


### Get Tag by TagName
@tagId = 1c9f54c59df9
GET {{host}}/api/tags/{{tagId}}