// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFCoreHooksConsole.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EFCoreHooksConsole.Models;

namespace EFCoreHooksConsole.Data
{
    public partial class EfhookdbContext : DbContext
    {
        public EfhookdbContext()
        {
        }

        public EfhookdbContext(DbContextOptions<EfhookdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ShopDefault> ShopDefault { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ShopDefault>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.ShopDefault_CreatedDateTime).HasColumnType("datetime");

                entity.Property(e => e.ShopDefault_CreatedUser)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ShopDefault_GroupTypeDef)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.ShopDefault_Id).ValueGeneratedOnAdd();

                entity.Property(e => e.ShopDefault_Key)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.ShopDefault_UpdatedDateTime).HasColumnType("datetime");

                entity.Property(e => e.ShopDefault_UpdatedUser)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ShopDefault_Value).HasMaxLength(200);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}